baseURL = "/"
languageCode = "en-us"
title = "Desire Lines"
theme = "PaperMod"
pagination.pagerSize = 20
enableInlineShortcodes = true

[params]
  author = "Kristin Gannon"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  disableThemeToggle = false
  defaultTheme = "auto"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Audio"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Zine"
    url = "/zine/"
    weight = 2